### ISSUE TITLE
Build error on 1.14.9, Missing "./local" specifier

### ISSUE THREAD

**Issue by cmjoseph07** [vincjo/datatables#100]
`
[WebServer] x Build failed in 912ms
[WebServer] error during build:
[commonjs--resolver] Missing "./local" specifier in "@vincjo/datatables" package
`

I am using svelte "4.2.18" and vite "5.2.13"

**Comment by vincjo** [comment]
Thx for notifying.
I think i understand why. You probably import from `@vincjo/datatables/local`

Hopefully it is.

I published a `1.14.10` with that path

If you enconter any other issue, stick to `1.14.5`, there will be no more changes or fixes until 2.0.

**Comment by cmjoseph07** [comment]
@vincjo 

Sorry I did not get back to you on this, this did in fact resolve my problem. Thank you for the quick reply!
