### ISSUE TITLE
await handler search?

### ISSUE THREAD

**Issue by BerndtDavid** [vincjo/datatables#107]
Hello - I have a 10,000+ row table. After entering a search phrase, it can take up two seconds to update the table. Is there a way I can track the search progress - so I can display some sort of status spinner while it's updating?  Thanks.

![models](https://github.com/vincjo/datatables/assets/32177667/e6821d40-70d0-437d-b398-4c430c8b4372)

**Comment by vincjo** [comment]
Hello,
Depends on where data is updated. 

- Is it on server side, do you fetch data while user is searching?
- Is it a client side search, you load 10_000 rows and apply search on it?

For both I guess there is a possibility but in different ways

**Comment by iwazowsky** [comment]
@vincjo  Is there a workaround with serverside data at the moment?

**Comment by vincjo** [comment]
For example by adding a `isLoading` state in your data fetching function.  
It requires to create a store.

```ts
handler.onChange(async (state) => {
    isLoading.set(true)
    // [await fetching data....]
    isLoading.set(false)
    return data
})
```

Not ideal but at least, you have access to a "pending" state each time your data is loaded.
