### ISSUE TITLE
Pagination breaks after rows per page change

### ISSUE THREAD

**Issue by DVDAndroid** [vincjo/datatables#11]
1. Go to [https://vincjo.fr/datatables/tutorial/pagination](https://vincjo.fr/datatables/tutorial/pagination) example
2. Select page 9
3. Change value of number entries to 100
4. Result: empty table, incorrect page selected

Possible fixes or workarounds:
- select the first page after row count change (ideal fix)
- expose an "event" to `triggerChange` to manually change page to the first one

**Comment by vincjo** [comment]
Indeed, thx
maybe a `setRowsPerPage` method is missing. This would allow the event to be handled automatically.
In the meantime I added  `on:change` in select element :

````svelte
    <select bind:value={$rowsPerPage} on:change={() => handler.setPage(1)}>
        {#each options as option}
            <option value={option}>
                {option}
            </option>
        {/each}
    </select>

````
