### ISSUE TITLE
[Suggestion] Responsive Design

### ISSUE THREAD

**Issue by Walker088** [vincjo/datatables#12]
Hi man
First of all, I'd like to say this is an awesome project!
But I am just wondering if you have any plans to introduce some mobile-friendly features to the project,
like this one for instance [Jquery DataTable Responsive Extension](https://datatables.net/extensions/responsive/examples/styling/bootstrap5.html)

**Comment by vincjo** [comment]
Hi man

Yes, this approach looks quite interesting, thanks for the suggestion.

I don't plan to go in that direction at the moment (especially if it would require DOM manipulation).

Afterwards, if someone wants to open a PR, it is not completely ruled out
