### ISSUE TITLE
Disable Search and Pagination

### ISSUE THREAD

**Issue by zogs** [vincjo/datatables#13]
Would be nice to be able to disable these feature by config ! 
in my particular case i don't need it so i masked it by CSS ...

Also had trouble figuring how to use reactivity using $: handler.setRows(data) ... maybe you can add a example in the docs !

On the whole pretty usefull library. Starred :)

**Comment by vincjo** [comment]
True, it can be handy.
I made the changes in `1.2.0`
Complete example here : https://vincjo.fr/datatables/examples/blocks

About the reactivity, yes absolutely I will add a complete example. Thanks for pointing it out to me

**Comment by zogs** [comment]
Perfect. Thank you !
