### ISSUE TITLE
Allow Customization of `rowsPerPageOptions` in `RowsPerPages` Component

### ISSUE THREAD

**Issue by Johjoh-6** [vincjo/datatables#130]
Currently, the **RowsPerPages** component has hardcoded options for the number of rows per page. In the Local, the options are set as:

```js
const options = [5, 10, 20, 50, 100];
```

In the Remote, the options are set as:

```js
export let options = [5, 10, 20];
```

## Proposal
It would be beneficial to allow customization of these options similar to how internationalization (i18n) settings are handled. This would provide more flexibility for users to define their own set of options.

### Example
Here is an example of how this could be implemented:

```js
const handler = new DataHandler(myData, {
    rowsPerPage: 10,
    rowsPerPageOptions: [10, 25, 50], // Customizable options
    i18n: {
        search: 'Rechercher...',
        show: 'Afficher',
        entries: 'lignes',
        filter: 'Filtrer',
        rowCount: 'Lignes {start} à {end} sur {total}',
        noRows: 'Aucun résultat',
        previous: 'Précédent',
        next: 'Suivant'
    }
});
```

**Comment by vincjo** [comment]
i agree, thx for the suggestion.

V2 brings `options` parameter in `RowsPerPage` component:

```svelte
<script>
    import { RowsPerPage } from '@vincjo/datatables'
</script>

<RowsPerPage {table} options={[5, 10, 20, 50, 100]}/>
```

This component is shared between client-side and server-side pagination modes.
```ts
import { RowsPerPage } from '@vincjo/datatables/server'
// same component
```
