### ISSUE TITLE
Clear selected

### ISSUE THREAD

**Issue by timk** [vincjo/datatables#133]
Is there a way to clear/de-select all selected rows?

The way I've worked around it is once updated all selected rows as a group, I can run `selectAll()` twice, as a way to clear the selection. This poses UI updates and unnecessary processing. The other way around it is to subscribe to changes then iterate through a shadow array to call `select()` on each row, this also seems not optimal.
```ts
async function handleClearSelection() {
	handler.selectAll()
	handler.selectAll()
}
```

**Comment by vincjo** [comment]
Sorry for the late response.

Actually you can access an array of selected rows as a writable store, by using `handler.getSelected()`

So the best way would be: 
```ts
const selected = handler.getSelected()

function handleClearSelection() {
    $selected = []
}
```

If your function runs outside of a Svelte component:
```ts
function handleClearSelection() {
    handler.getSelected().set([])
}
```
