### ISSUE TITLE
Error "RangeError: Maximum call stack size exceeded" on clearSearch()

### ISSUE THREAD

**Issue by evapastors** [vincjo/datatables#134]
I'm using the runes version and whenever I call table.clearSearch() I get the error "RangeError: Maximum call stack size exceeded".

I created this minimal example of a table with a searchbar: 

```svelte
 <script lang="ts">
  import { TableHandler } from "@vincjo/datatables";

  const test: { name: string; address: string }[] = [
    { name: "Max Mustermann", address: "Example Street 1" },
    { name: "Test Person", address: "Street 2" },
  ];

  const handler = new TableHandler(test);

  const search = handler.createSearch(["name"]);

  const onReset = () => {
    handler.clearSearch();
  };
</script>

<input type="text" bind:value={search.value} oninput={() => search.set()} />

<div>
  {#each handler.rows as row}
    <div>
      <div>{row.name}</div>
    </div>
  {/each}
</div>

<button type="button" onclick={onReset}>Clear</button>
```
<img width="329" alt="Bildschirmfoto 2024-10-16 um 13 49 34" src="https://github.com/user-attachments/assets/190b2038-74fa-4cfe-97fe-e77e38f2a76a">

**Comment by vincjo** [comment]
Thx for the repro.
I wouldn't have noticed this one. The internal event dispatcher caused the error.
Fix published in `2.0.0-runes.45`
