### ISSUE TITLE
Mutating state inside a derived isn't allowed

### ISSUE THREAD

**Issue by knd775** [vincjo/datatables#137]
`allRows` calls `createAllRows`, which mutates `currentPage`. This isn't allowed, and svelte 5.1.0 started enforcing this more strictly. This leads to the following exception:
![image](https://github.com/user-attachments/assets/10dbd592-1cbb-4fbb-940f-fa58dc1e374e)

https://github.com/vincjo/datatables/blob/015a248765fad21c9f0c6c1ed76ecf9a4ce3f6b9/src/lib/src/client/AbstractTableHandler.svelte.ts#L22
https://github.com/vincjo/datatables/blob/015a248765fad21c9f0c6c1ed76ecf9a4ce3f6b9/src/lib/src/client/AbstractTableHandler.svelte.ts#L58-L74

**Comment by vincjo** [comment]
THANKS. 
Just moved the "back to first page" instruction in the setters instead.
published in 2.0.5
