### ISSUE TITLE
(runes) - state_unsafe_mutation

### ISSUE THREAD

**Issue by kevpye-fabdata** [vincjo/datatables#138]
Hi, first of all thank you for all of your work on this library. Now that the official release of Svelte 5 is available we are starting to update our code and so it was great to see that V2 of this library is already written in Svelte 5 and I was looking forward to updating.

I think however I have discovered a pretty major bug in V2. It seems like you cannot use the DataTable search / filter functionality in any component that accepts props - any props at all. 

Here is an example component called DataTableDemo.svelte - just using the hello world example code and data: As you can see I am doing nothing with the props, just the fact that I have props breaks the the global search and the column filters - triggering the state_unsafe_mutation error in the console. Clicking the headers for sort triggers the same warning from the other runes issue. Simply commenting out the line `const props: Props = $props();` removes the issue but of course this is not really a solution..

```svelte

<script lang="ts">
	import { TableHandler, Datatable, ThSort, ThFilter } from '@vincjo/datatables';
	const data = [
		{ id: 1, first_name: 'Tobie', last_name: 'Vint', email: 'tvint0@fotki.com' },
		{
			id: 2,
			first_name: 'Zacharias',
			last_name: 'Cerman',
			email: 'zcerman1@sciencedirect.com'
		},
		{ id: 3, first_name: 'Gérianna', last_name: 'Bunn', email: 'gbunn2@foxnews.com' },
		{ id: 4, first_name: 'Bee', last_name: 'Saurin', email: 'bsaurin3@live.com' }
	];

	interface Props {
		donkey?: boolean;
	}

	const props: Props = $props();

	const table = new TableHandler(data, { rowsPerPage: 10 });
</script>

<Datatable basic {table}>
	<table>
		<thead>
			<tr>
				<ThSort {table} field="first_name">First Name</ThSort>
				<ThSort {table} field="last_name">Last Name</ThSort>
				<ThSort {table} field="email">Email</ThSort>
			</tr>
			<tr>
				<ThFilter {table} field="first_name" />
				<ThFilter {table} field="last_name" />
				<ThFilter {table} field="email" />
			</tr>
		</thead>
		<tbody>
			{#each table.rows as row}
				<tr>
					<td>{row.first_name}</td>
					<td>{row.last_name}</td>
					<td>{row.email}</td>
				</tr>
			{/each}
		</tbody>
	</table>
</Datatable>

```
Here is a screen shot showing the errors / warnings. The warning comes from clicking the table header to sort. The error comes from trying to filter. 

<img width="1667" alt="image" src="https://github.com/user-attachments/assets/8c6ecc39-9098-4995-a01c-104a153e4729">

Thanks

**Comment by vincjo** [comment]
Thx for the repro.
After 1 month I wasn't sure but it seems i already fixed the issue.

### CHANGELOG 2.0.5 - 2024-10-24
- fix: `state_unsafe_mutation` error. currentPage is mutated in setters instead: filter.set() / search.set().


I tried the component based on your example and got no error. If the problem persists, just let me know
