### ISSUE TITLE
minor improvement: css-classes on Components

### ISSUE THREAD

**Issue by michapixel** [vincjo/datatables#14]
eg. the Pagination Component has no class whatsoever.
Would be cool if Components could be written in this way too:
```
<Pagination 
   class="dt_pagination"
   handler={ dataTable }  
/>
```

Inside of the Component it can be done in this way:

```
<section class="{ if $$props.class !== undefined ? $$props.class : '' }">
```

Don't know if this is the official way, but i found it on the webs and it was very useful for me.

**Comment by vincjo** [comment]
I would recommend creating your own paging component
The handler provides all pagination features :

````ts
const pages = handler.getPages({ ellipsis: true }) 
console.log($pages)
````
result :
````ts
[ 1, 2, 3, 4, 5, null, 24 ]
````
Svelte template :
````svelte
{#each $pages as page}
    <button on:click={() => handler.setPage(page)}>
        {page ?? '...'}
    </button>
{/each}
````

Then you have complete control over styling  in a minimal logic imlementation.

That being said, let me know if you still prefer that I implement a class property

**Comment by vincjo** [comment]
Great
thx for your message
:duck: :duck:
