### ISSUE TITLE
Search does not work correctly in svelte 5

### ISSUE THREAD

**Issue by targetss** [vincjo/datatables#140]
Hi, I discovered a problem when switching to svelte 5. If, when initializing a table, we specify the “highlight” parameter, then the search result breaks

`const table = new TableHandler(data, {rowsPerPage: 10, i18n: i18nRUS, highlight: true})`

![Screenshot_1](https://github.com/user-attachments/assets/83682218-8cf8-4795-acb5-2bb790fcdd35)

**Comment by vincjo** [comment]
Hi,
Seeing your example, if I understand correctly, it seems to work fine. 
The `hightlight: true` param wraps matching values between some html `<u class="highlight">`.
You need to add `@hmtl` in your template so svelte is able to render this HTML.
