### ISSUE TITLE
Table doesn't dynamically render Svelte 5?

### ISSUE THREAD

**Issue by ddxv** [vincjo/datatables#141]
I want the table to dynamically render / recreate when sent new data.  For example:

`MyTable.svelte`
```ts
let {
		data = [] as MyEntry[],
		dimensionA,
		dimensionB
	} = $props();


	const table = new TableHandler(
        data,
         { rowsPerPage: 10 }
        )
```

And when I update the data in `+page.svelte` with drop downs / filters, while I can see this is passed correctly into `MyTable.svelte`, in fact the table headers will update. The table data in the rows does not update correctly.

What is the correct way to pass the data into TableHandler so that it works with the Svelte 5 reactive runes?

**Comment by VibingCreator** [comment]
You should use `table.setRows()` method to handle inserting or updating table data and `$effect` will take care of the rest.

[Docs...](https://vincjo.fr/datatables/api/client/methods~setRows)

**Comment by ddxv** [comment]
Thank you, I appreciate it!
