### ISSUE TITLE
Are you sure you need a cryptographically secure id for sort and filter operations? 

### ISSUE THREAD

**Issue by bn-l** [vincjo/datatables#146]
Sadly this breaks the component for me when I am connecting to my dev server from another computer on my network (the --host option for vite). The browser won't let you call the method unless you're on local host or https.

Why wouldn't math.random suffice here?

**Comment by vincjo** [comment]
Indeed math.random is sufficient to generate identifiers for the filters

**Comment by vincjo** [comment]
Thx for your contribution. Published on npm: `2.1.0`
