### ISSUE TITLE
How to sort a date like MM/DD/YYYY hh:mm:ss A ?

### ISSUE THREAD

**Issue by Hedronmx** [vincjo/datatables#149]
I am breaking my head on how can i sort a column based off that date format. Any ideas? Thanks!

**Comment by vincjo** [comment]
There is a way, by refining your date field in a callback function.
It must return a value of type string with `YYYY-DD-MM hh:mm:ss` format (ISO string).

For example: 
```ts
const sort = table.createSort(row => new Date(row.your_date_field).toISOString())
```

**Comment by vincjo** [comment]
Added an example based on your use-case in the documentation:
https://vincjo.fr/datatables/docs/client/sort/dates

**Comment by Hedronmx** [comment]
Excellent! Thanks

**Comment by Hedronmx** [comment]
Sorry for the double reply. But could this be possible on v1 of datatables? My project runs on svelte 4. Thanks! Appreciate your time!
