### ISSUE TITLE
How to properly update table data after action 

### ISSUE THREAD

**Issue by cezaryszymanski** [vincjo/datatables#151]
Hi

I am in a process of migration from v1 to v2
I have a table with action to edit records. There's a POST server action for edit after which the +page.server.ts load function runs and I get the updated data

After this in v1 I could simply update the table data with:
handler.setRows(newData)

But in v2 API there's no such function. What is the right way to update table data then?
For now I am using table.invalidate() but this loads the data for the second time for no reason

Maybe I don't understand the current API correctly?

**Comment by vincjo** [comment]
Hi

Indeed `setRows` method doesn't exist anymore in server-side mode.

Instead of adding a setter, in your case, I think a simple `table.rows = newData` is enough since there are no other side events to handle.

**Comment by cezaryszymanski** [comment]
It works that way, thanks!

I assumed that this is read-only property and it won't have any effect
