### ISSUE TITLE
[Suggestion] Add 'locales' and 'options' optional parameters for localeCompare used in sortAsc/sortDesc

### ISSUE THREAD

**Issue by mattpurlandncc** [vincjo/datatables#16]
Is there any change of getting these added? Seeing as they can be optional it shouldn't break compatibility.

Apologies, I'm short on time and can't really provide a PR

**Comment by vincjo** [comment]
I haven't found an elegant way to implement these parameters.

I'll have to take the sorting system back and improve it a bit
