### ISSUE TITLE
[Suggestion] Add 3rd paramter type of Object to allow sorting using returned format of getSorted()

### ISSUE THREAD

**Issue by mattpurlandncc** [vincjo/datatables#17]
I'm not sure if the title makes sense, but I'd like to be able to sort like the following:

```
handler.sort({
    identifier: 'column_name',
    direction: 'desc'
});
```

This is the same format as getSorted() and would allow me to pass these via the URL to the backend:

http://localhost?sort[identifier]=column_name&sort[direction]=desc

Which could be sent as a prop to the frontend so I can sort the data on page load

**Comment by vincjo** [comment]
Ok. There's a new method `handler.applySorting()`, that could fit with your use case.

Bellow are the params :
````ts
handler.applySorting({
    orderBy: 'column_name',
    direction: 'asc'
})
````

**Comment by MattPurland** [comment]
@vincjo any chance it can be 'identifier' instead of 'orderBy'? That way it matches that of getSorted() output

**Comment by vincjo** [comment]
unfortunately, "identifier" = "orderBy.toString()", it can't be of type Function

"orderBy" can be a callback function, not "identifier"
