### ISSUE TITLE
Remote search and pagination

### ISSUE THREAD

**Issue by thelinuxlich** [vincjo/datatables#19]
An example would be awesome!

**Comment by vincjo** [comment]
**Base component :**
````svelte
<script>
    import { DataHandler } from '@vincjo/datatables'
    import { myJSON } from 'somewhere'
    import RemoteSearch from './RemoteSearch.svelte'
    import RemotePagination from './RemotePagination.svelte'

    const handler = new DataHandler(myJSON, { rowsPerPage: 10 })
</script>

<RemoteSearch {handler}/>

<RemotePagination {handler}/>
````

**RemoteSearch.svelte :**
````svelte
<script>
    export let handler
    let value = ''
</script>

<input type="text" bind:value on:input={() => handler.search(value)} />
````

**RemotePagination.svelte :**
DataHandler getters return derived stores that update  according pagination state.
````svelte
<script>
    export let handler
    const pageNumber = handler.getPageNumber()
    const pages = handler.getPages({ ellipsis: true }) 
</script>

<button on:click={() => handler.setPage('previous')}>
    Previous
</button>

{#each $pages as page}
    <button type="button"
        class:active={$pageNumber === page}
        on:click={() => handler.setPage(page)}
    >
        {page ?? '...'}
    </button>
{/each}

<button type="button" on:click={() => handler.setPage('next')}>
    Next
</button>
````

**Comment by vincjo** [comment]
I did'nt understand your request.
This lib only handles client-side interactions with data. No opinion on the data fetching part

I saw this repo recently, which seems to focus on server-side processing
https://github.com/Parazeya/svelte-flextable

maybe you will find more answers there

**Comment by thelinuxlich** [comment]
Hmm interesting, why this project looks so similar to yours?

**Comment by vincjo** [comment]
I guess it extends mine ? idk
The author clearly started from my code base, including for the documentation site …

**Comment by riziles** [comment]
@vincjo Looks like he has acknowledged you. What are your thoughts on it?

**Comment by vincjo** [comment]
Hello @riziles
I was able to contact the author, who immediately agreed to add the credits.
Personally I have no problem with reusing/copying code from this lib. Credits are highly appreciated but not required (unless the documentation site is exactly the same)

I won't be able to respond positively to all feature requests (especially  edge cases) to keep things as simple as possible. That's why I have no problem with other developers taking over this project for their needs

**Comment by riziles** [comment]
Cool. I appreciate that.
