### ISSUE TITLE
gettings errors in Row.js 

### ISSUE THREAD

**Issue by michapixel** [vincjo/datatables#22]
I'm getting errors when i try to re-set all Rows (reload json-Data) in Row.js
orderBy is null somehow and that fails.  The data i'm fetching is exactly the same. 

i fixed that temporarily by catching this case in this way:

```
parse(orderBy) {
        // ---- INSERT
        if(orderBy === null) {
            return {
                fn: () => {},
                identifier: 'null',
            }
        }
        // ----
        if (typeof (orderBy) === 'string') {
            return {
                fn: (row) => row[orderBy],
                identifier: orderBy.toString()
            };
        }
        return {
            fn: orderBy,
            identifier: orderBy.toString()
        };
    }
```

**Comment by vincjo** [comment]
Thx @michapixel 

Not sure if I reproduced the error perfectly, but it should be fixed in 1.4.1, just published.

If "orderBy" is nullish, `sort`, `sortAsc` and `sortDesc` methods are aborted
