### ISSUE TITLE
How to access value of Th Filter

### ISSUE THREAD

**Issue by JLLMNCHR** [vincjo/datatables#25]
In the following scenario, the filter is still applied, but the **value is not displayed**:

1. Fill the Id filter with something, for example "ab". (The filter is applied correctly.)
2. Click the New button to register a new element.
3. I hit the Back button.
4. It is observed that the filter is still applied, BUT the value "ab" has disappeared:

Some help will be appreciatted. Maybe some public method in Filters.ts to access the value of each filter or something like that...

Thanks in advance!

![image](https://user-images.githubusercontent.com/53475407/229124459-6b379011-6fe1-406f-823a-99c5d1751c6c.png)
![image](https://user-images.githubusercontent.com/53475407/229124506-745a696c-04d4-4d10-b32d-d719ff25261c.png)
![image](https://user-images.githubusercontent.com/53475407/229124533-28a38999-f0f2-4ecb-ae3c-19c755067d52.png)

**Comment by vincjo** [comment]
Thanks for the illustration.

It seems that the value is correctly registred into the filters store. But when you go back, `ThFilter` component is remounted with the default filter value which is an empty string `''`.

If you can keep your table component behind your create form - for example by using a modal, you won't have this problem anymore (I guess currently your table component is destroyed, replaced by a form and then remounted after form validation)

To my knowledge there is no simple way to bind the input value (DOM) to the applied filter

Alternatively, you can use the `handler.clearFilters()` method which removes all applied filters

**Comment by vincjo** [comment]
To illustrate, this way the filter value won't disapear :
![image](https://user-images.githubusercontent.com/37813278/229820186-6f913573-90d0-4ace-a7e0-34a3788accdb.png)
