### ISSUE TITLE
[Suggestion] CSS classes on components

### ISSUE THREAD

**Issue by PercivalFigaro** [vincjo/datatables#29]
Hello!

This was already mentioned in [Issue #14](https://github.com/vincjo/datatables/issues/14), but it would be very helpful if styling could be applied to different components (Pagination, Search, RowsPerPage, ThFilter etc) without remaking all of those components. 

The project I'm working on uses the Skeleton UI toolkit. The developers of Skeleton suggested using your datatable as a great replacement to what they are intending to make (since they have not implemented theirs yet), but currently, on a project with a dark background design, this datatable component is very hard to work with - I would have to remake many things from scratch just to change the font color to something readable.

Thanks!

**Comment by vincjo** [comment]
Hello

Yes no problem if it can be helpful.
So basically I added a class prop to each component (thx to @michapixel for suggestion)

````svelte
<Datatable class="something"/>
<Pagination class="smthg else"/>
<!-- etc. -->
````
Example:
https://vincjo.fr/datatables/test

But I still recommend creating your own components :) 

- `ThFilter`, `Search` = text-input
- `Th` = `<th>` with a click event for sorting data
- `RowsPerPage` = `<select>`
- `RowCount` = `<p>`
- `Pagination` = button goup 

(probably 2-3h of reverse engineering)

**Comment by PercivalFigaro** [comment]
Thanks a lot!
