### ISSUE TITLE
Feed data and pagination from backend api

### ISSUE THREAD

**Issue by kefahi** [vincjo/datatables#30]
Thank you for the amazing and elegant work!

My use case, involves having a headless CMS that provides api to access, paginate, filter and sort the data. The number of data rows is in the millions and hence can not be pre-fetched.

I was wondering if it is easy to connect datatables with arbitrary backend api (so the data is not all readily available) where we can retrieve the data for each page and apply any necessary filtration / sorting. All done for a backend api. 

Should I, with my case above, implement/extend DataHander class?

**Comment by stepollo2** [comment]
+1 i need to load lot of data and it would be nice to see an example of server side pagination

**Comment by vincjo** [comment]
Currently this lib can't help at all in the case where the data processing logic applies on the server side (searching, filtering, paging, sorting...)
I'm working on it.

In any case, if you are looking for something operational right away, there are surely more advanced tools than this one

**Comment by vincjo** [comment]
Currently we need an handler that can trigger requests to fetch the data once table state changes.
The major concern will be to provide something fairly universal because there are a lot of different API designs.

Maybe by using a derived store to get the table state:

````ts
const params = handler.getState()
// params: 
{ 
    search: 'john', 
    page: { number: 2, offest: 40, limit: 20 }, 
    rowsPerPage: 20, 
    sort: [ { key: 'first_name', direction: 'asc' }, {key: 'last_name', direction: 'asc'} ] 
}

// users?per_page=20&offset=40&search=john

const response = await fetch(`/users?per_page=${params.rowsPerPage}&offset={params.page.offset}&search=${params.search}`)
````

**Comment by PercivalFigaro** [comment]
+1, this feature would be much appreciated. Will be working with millions of table entries, so front-end pagination and operations really isn't an option

**Comment by vincjo** [comment]
Made a draft implementation with some examples using public APIs.
http://localhost:5173/datatables/remote/examples

We must define an api-specific `reload()` function which is triggered at each change of state.
````ts
handler.onChange( (state) => reload(state) )
````

The reload function is triggered using the following method:
````ts
handler.invalidate()
````

More details here:
https://vincjo.fr/datatables/remote/basic-usage

**Comment by keytrap-x86** [comment]
@vincjo Where did that page go ? I'm tring to use remote data also

**Comment by vincjo** [comment]
If you're working in a Svelte 3/4 project, you can refer to this page: 
https://vincjo.fr/v1datatables/remote/basic-usage

Using Svelte 5 & SSD v2:
https://vincjo.fr/datatables/docs/server/getting-started/overview
