### ISSUE TITLE
Filtering table columns and numbers

### ISSUE THREAD

**Issue by silverliiv** [vincjo/datatables#32]
Hey, first of all thanks for the great package, it has worked out great so far.

But I recently stumbled onto a smallish issue.

I have tables and columns with filtering, and filtering numbers does work from 1-9 but not if it gets higher.
For example I have these data rows with values: AVG8, AVG10, AVG11

The filtering works like that:
AVG8, AVG11, AVG10 OR AVG10, AVG11, AVG8

Meaning it's only taking into consideration the first part, not the whole number.
I also attached some images to understand it better.

<img width="580" alt="image" src="https://github.com/vincjo/datatables/assets/7254643/1f61161f-463a-4bc3-ac4d-e518de8596f6">
<img width="570" alt="image" src="https://github.com/vincjo/datatables/assets/7254643/028f944e-e253-42a3-9b5c-46cebac4e831">

**Comment by riziles** [comment]
@silverliiv , Is this a question about sorting or filtering?

**Comment by silverliiv** [comment]
I'm using this "Th" component (attached a screenshot).
<img width="597" alt="image" src="https://github.com/vincjo/datatables/assets/7254643/90c8442d-eb61-4791-b9ff-0ddcb705837c">

I think it's sorting then yes, sorry for the mess.

**Comment by vincjo** [comment]
Hey,

Indeed, values ​​are sorted as strings, "8" > "<ins>**1**</ins>1"

If it's possible you can cast these string values as numbers with a callback. 
it would look like this:
````svelte
<Th 
    {handler} 
    orderBy={(row) => Number(row.avg_stack.replace('AVG', ''))}
>
    AVG Stack
<Th/>
````

**Comment by silverliiv** [comment]
Perfect, solution worked nicely. Thank you.
