### ISSUE TITLE
[ERROR] Could not resolve "$lib"

### ISSUE THREAD

**Issue by mapl** [vincjo/datatables#34]
After updating to the latest version 1.9.4 (coming from 1.7.2), I am getting an error.

VITE v4.3.9  ready in 677 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
X [ERROR] Could not resolve "$lib"

    node_modules/@vincjo/datatables/Datatable.svelte:39:58:
      39 │ import { Search, RowsPerPage, RowCount, Pagination } from '$lib';
         ╵                                                           ~~~~~~

  You can mark the path "$lib" as external to exclude it from the bundle, which will remove this
  error.

**Comment by vincjo** [comment]
thank you so much for pointing it out

Should be better with `1.9.5`
