### ISSUE TITLE
Bug: setRows() changes getSorted store

### ISSUE THREAD

**Issue by MattPurland** [vincjo/datatables#37]
I've discovered an issue where if setRows() is used to apply new data the contents of the getSorted store goes from this (for example):

`{identifier: 'Supplier Name', direction: 'asc', fn: ƒ}`

to this:

`{identifier: '(row) => row[orderBy]', direction: 'asc', fn: ƒ}`

The data in the table itself is sorted correctly, but visually (the <Th> component) no longer displays the correct sorting direction (based on your <Th> example)

**Comment by vincjo** [comment]
Thanks for pointing it out
bug fix just realeased in `1.10.4`
