### ISSUE TITLE
Question: Is there way to add action buttons to edit delete a row?

### ISSUE THREAD

**Issue by dnaicker86** [vincjo/datatables#49]

**Comment by vincjo** [comment]
There is currently no method or component to edit/delete or create a row.

But it is relevant and will probably be added in a future release

**Comment by AngeloAnolin** [comment]
This implements the above request.

https://vincjo.fr/datatables/reactivity

Posting the code would be helpful.

**Comment by macellinoss275** [comment]
I don't see the need to do this as this is not Svelte DataTables problem. Pretty sure all you need to do is just create 2 buttons, make back-end functions related to those buttons and that's all. Since Svelte DataTables could automatically add or remove the row (or data) anyway.
