### ISSUE TITLE
is it possible to detach search and pagination

### ISSUE THREAD

**Issue by michapixel** [vincjo/datatables#5]
the predecessor could do that ...

**Comment by vincjo** [comment]
thanks for asking

The approach is a little different,
here the components are provided as examples with minimal configuration.

the goal is to easily adapt to as many contexts as possible. 
However it requires a little more work to start, it won't suit everyone.

To summarize, you create your own datatable component

````svelte
<script lang="ts">
    import { DataHandler, Th, ThFilter, RowsPerPage, RowCount } from '@vincjo/datatables'

    const handler = new DataHandler(myData, { rowsPerPage: 10 })
    const rows = handler.getRows()
</script>

<header>
    <RowsPerPage {handler}/>
</header>

<table>
    <!-- stuff -->
</table>

<footer>
    <RowCount {handler}/>
</footer>
````

**Comment by vincjo** [comment]
I was wrong, it turns out to be very useful to make these components optional.
Just updated
https://vincjo.fr/datatables/examples/blocks
