### ISSUE TITLE
Row selection - scope set to currentPage

### ISSUE THREAD

**Issue by R3quest** [vincjo/datatables#50]
[Docs](https://vincjo.fr/datatables/api#row-selection) mention that we can set scope to currentPage,
When trying out row selection [example](https://vincjo.fr/datatables/examples/row-selection) and passing handlers selectAll method object `{ selectBy: "id", scope: "currentPage" }` and testing it out, it seems like it is not working as expected.

Try clicking on Th checkbox and switching pages, or deselecting checkbox on single row it seems like it doesn't update as expected.

**Comment by vincjo** [comment]
Thx for reporting it.

It is indeed broken, I didn't cover all use-cases for row selection.

I can fix it quick but i wonder what should happen if the user change the current page?
- Deselect rows on previous page ?
- Keep selection on previous page ?


Any idea welcomed

**Comment by R3quest** [comment]
Depending on what is better for UX, not sure what would be better but:

- if selection is kept on previous page - it might be confusing for users when sorting columns to keep track on selection

Works in version `1.12.2` as you have mentioned :100:

**Comment by vincjo** [comment]
Thanks, you are right. 
I leave as is for now 👍
