### ISSUE TITLE
'slice' error when no record is received

### ISSUE THREAD

**Issue by etuncay** [vincjo/datatables#56]
Hello
I get an error when there is no record.

---------------handler---------------------------
{"context":{"event":{"events":{"change":[],"clearFilters":[],"clearSearch":[]},"triggerChange":{}},"rowsPerPage":{},"pageNumber":{},"search":{},"filters":{},"filterCount":{},"rawRows":{},"filteredRows":{},"pagedRows":{},"rowCount":{},"pages":{},"pagesWithEllipsis":{},"pageCount":{},"sort":{},"selected":{},"selectScope":{},"isAllSelected":{}},"sortHandler":{"rawRows":{},"event":{"events":{"change":[],"clearFilters":[],"clearSearch":[]},"triggerChange":{}},"sort":{},"backup":[]},"selectHandler":{"filteredRows":{},"pagedRows":{},"selected":{},"scope":{},"isAllSelected":{},"event":{"events":{"change":[],"clearFilters":[],"clearSearch":[]},"triggerChange":{}}},"pageHandler":{"pageNumber":{},"rowCount":{},"rowsPerPage":{},"event":{"events":{"change":[],"clearFilters":[],"clearSearch":[]},"triggerChange":{}}},"searchHandler":{"search":{},"event":{"events":{"change":[],"clearFilters":[],"clearSearch":[]},"triggerChange":{}}},"filterHandler":{"filters":{},"event":{"events":{"change":[],"clearFilters":[],"clearSearch":[]},"triggerChange":{}}},"i18n":{"search":"Search...","show":"Show","entries":"entries","filter":"Filter","rowCount":"Showing {start} to {end} of {total} entries","noRows":"No entries found","previous":"Previous","next":"Next"}}

TypeError: $filteredRows.slice is not a function

![image](https://github.com/vincjo/datatables/assets/1586387/7504ca47-7433-4895-b0fa-6927f23a6533)

**Comment by vincjo** [comment]
Hello

`DataHandler` can  take an empty array as first parameter.

````ts
// it works
const handler = new DataHandler( [] )

// it works
handler.setRows( [] )
````

If you don't pass an iterable data, you'll get the `TypeError: $filteredRows.slice is not a function` error.


Please let me know if this is due to another issue
