### ISSUE TITLE
Sorting with Nested Objects

### ISSUE THREAD

**Issue by MrVauxs** [vincjo/datatables#59]
Hi, is there a way to sort using a nested object, like `name.primary`?
Alternatively, it would be nice to be able to provide your own sorting function.

**Comment by vincjo** [comment]
Hi,

There is a way:
```ts
handler.sort( (row) => row.name.primary )
```

Using `Th` component:
```svelte
<Th {handler} orderBy={(row) => row.name.primary}>
    Primary
</Th>
```

Thx for your suggestion, will think about it

**Comment by vincjo** [comment]
At the moment I don't figure out what problem a custom sorting function could solve.
if you have more ideas about it, don't hesitate to post a new issue/suggestion
