### ISSUE TITLE
[Bug] change event not triggering after using setRows

### ISSUE THREAD

**Issue by mattpurlandncc** [vincjo/datatables#69]
As per the description, I'd expect the change event to trigger should the data change via setRows.

**Comment by vincjo** [comment]
Added in `1.12.6`

So far I only use it to sroll up. It’s a pretty general event.

To summarize the 'change' event is triggered in the following situations:
- filtering
- removing filters
- searching
- removing search
- on page change
- sorting
- removing sorts
-  **+ after using setRows**

Please let me know if any side effects appear.
We can add a new / more specific event if necessary
