### ISSUE TITLE
Will there be support for Vue?

### ISSUE THREAD

**Issue by macellinoss275** [vincjo/datatables#73]
I have used your Datatables for my Laravel Inertia Svelte project before and honestly this is probably the easiest and the best Headless Datatables out there. But I wonder if you will ever make an integration of this for Vue 3? Thanks.

**Comment by vincjo** [comment]
This is not planned at the moment. 
I imagine it's possible to port the lib to other frameworks (by adding a store lib like Pinia). It's a good idea but tbh, I don't have the skills to propose anything other than Svelte. 
Of course if someone more knowledgeable wishes to study the question, PRs are wlc.
