### ISSUE TITLE
Zero rows shows as all selected

### ISSUE THREAD

**Issue by sgoth** [vincjo/datatables#78]
Related to the new remote "select all" feature from #75 there's a tiny bug when the table shows no rows.

Just entering a search term without a result shows it in the beer api example:

![image](https://github.com/vincjo/datatables/assets/1681610/468a77c9-ae18-4ff5-b32d-51918b38d4b3)
 
It's not technically false that "all of none" are selected but still i think it should be "false" here 😄

**Comment by vincjo** [comment]
Thx.
Just fixed in `1.14.1`
