### ISSUE TITLE
Single Filter Multiple Matches

### ISSUE THREAD

**Issue by Smith-Chris1** [vincjo/datatables#79]
Is it possible to have a single filter with multiple match criteria?

For example:

If I have 6 datacenters data1,data2,data3,data4,data5,data6
and I want to see the results in data1 and data4, is that possible?

my code looks like this:
handler.createFilter('data1', check.startsWith)

**Comment by vincjo** [comment]
Yes, it is possible.

For implementation, you'll need to use the 'create**Advanced**Filter' method instead.

```ts
const filter = filter.createAdvancedFilter('datacenter')
const selected = filter.getSelected()
```

Then, in markup side:
```svelte
<button on:click={() => filter.set('data1', check.isEqualTo)} class:selected={$selected.includes('data1')}>
     Datacenter 1
</button>
```
There are some examples here:
https://vincjo.fr/datatables/advanced-filters/multiple-criteria
