### ISSUE TITLE
Typescript  support

### ISSUE THREAD

**Issue by Rogerio940** [vincjo/datatables#8]
I install this npm and i m using in my project Typescript. 
Is show me this:
Could not find a declaration file for module '@vincjo/datatables'
If the '@vincjo/datatables' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module '@vincjo/datatables';

**Comment by Rogerio940** [comment]
i add this line in app.d.ts to solve the problem
declare module '@vincjo/datatables';

**Comment by vincjo** [comment]
I misread SvelteKit doc about packaging.

Now it exports the index.d.ts, it should work properly.

Thx for reporting :thumbsup:
