### ISSUE TITLE
Filter only working on first column for SSR

### ISSUE THREAD

**Issue by kmalloy24** [vincjo/datatables#82]
When I recreate it locally and `console.log` both `value` & `filterBy` in the component they seem to be working correctly as well as `params` from `api.ts`. 

![filter issue](https://github.com/vincjo/datatables/assets/35405191/003b1f3f-1066-41bf-9e23-06d07cf6812c)

**Comment by vincjo** [comment]
*jsonplaceholder* is the only free external API I could find to illustrate server-side column filtering.
Unfortunately, it is necessary to type the full title - or "true"/"false" in the "Completed" column - to get a result.

**Comment by kmalloy24** [comment]
ahhhh gotcha, good to know!
