### ISSUE TITLE
Search for integers don't work

### ISSUE THREAD

**Issue by saumil-ventura** [vincjo/datatables#9]
In my data I have 
{"id":1}
when i search 1 in filter or globa search, it doesn't work, and when i clear inputs it empties the table until I search for string.

**Comment by vincjo** [comment]
Indeed, an error in a previous update.

fixed : 
https://vincjo.fr/datatables/test


Thanks for reporting it

**Comment by saumil-ventura** [comment]
Thank you very much !!
