### ISSUE TITLE
Row selection with filtering issue

### ISSUE THREAD

**Issue by bfbay315** [vincjo/datatables#92]
In the example: https://vincjo.fr/datatables/examples/row-selection, I noticed that when you select a row, and then filter, the row becomes unselected.  

I see this when running in my project as well.  Using version 1.14.2

**Comment by vincjo** [comment]
It is how row selection is implemented for client-side in V1.
Any interaction will remove the selection, which is not ideal, i agree.

I have already upgraded the system but it results in a (small) breaking change, therefore postponed for the next major version
