### ISSUE TITLE
Filter and sorting with nested array in object

### ISSUE THREAD

**Issue by azern32** [vincjo/datatables#98]
I have data where the format goes like this
```
result : [
    0: {
      key1 : value1,
      ....,
      keyN : [
         0: {
              nestedN : valueN
         },
         1: {
              nestedN : valueN
         },
     ]
    },
    1: ...
]
```
The very top array will be the rows

How can I filter and sort by that "nestedN" ?

I tried using 
``` 
{handler} orderBy={(row) => row.keyN.nestedN} 
```
but it failed to do so. I figure this must be because the data to filter were inside an array. Yet, all the examples I see using just object.

Any help?

**Comment by vincjo** [comment]
#86
