### ISSUE TITLE
[SvelteKit] Build failure on version 1.14.6

### ISSUE THREAD

**Issue by Cluster2a** [vincjo/datatables#99]
Hey, using the latest Version, I am getting a build error and our pipeline fails:
![image](https://github.com/vincjo/datatables/assets/84905165/629ffab2-1e42-49bb-8d40-dd5e8b13cd83)

Reverting to version 1.14.5 fixes the issue.

I am using SvelteKit [2.5.10](https://www.npmjs.com/package/@sveltejs/kit/v/2.5.10) on node 22.

Best regards - alex

**Comment by vincjo** [comment]
Thank you so much. Sorry for the mess.

I was able to fix the problem, deprecate the corrupted versions and publish a working one: `1.14.9`.
